// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.clonk.ai/
// Generated: 2026-06-21T19:40:54.878Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#262626' | '#ffffff' | '#000000' | '#ff551d' | '#555555' | '#ff7a47' | '#f1f1f1' | '#101010' | '#1b1b1b' | '#676767' | '#dff58b' | '#e5e5e5' | '#757575';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = '__neueMontreal_8db69f' | '__stackSansText_3cee34' | '__degularDisplay_1e8a8c';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '700' | '500' | '300' | '900';

export type SpacingToken = '2px' | '48px' | '56px' | '64px' | '80px' | '96px' | '112px' | '127px' | '160px' | '173px' | '178px' | '200px' | '208px' | '232px' | '260px' | '279px' | '332px';

export type RadiusToken = '7px' | '11px' | '14px' | '18px' | '22px' | '26px' | '34px' | '38px' | '45px' | '48px' | '9999px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
